### ISSUE TITLE
Problem when modeling a specific table

### ISSUE THREAD

**Issue by zidenis** [stablekernel/aqueduct#160]
I'm trying to use aqueduct with a legacy database.
I have this table...
```sql
create table t_clinica (
   seq_clinica          SERIAL               not null,
   nom_clinica          VARCHAR(128)         not null,
   num_cnpj             NUMERIC(16)          not null,
   cod_cnes             NUMERIC(7)           null,
   ind_ativo            BOOL                 not null default TRUE,
   dta_insert           TIMESTAMP WITH TIME ZONE not null default CURRENT_TIMESTAMP,
   dta_update           TIMESTAMP WITH TIME ZONE not null default CURRENT_TIMESTAMP,
   constraint pk_clinica primary key (seq_clinica)
);
```
Then I modeled as follows...
```dart
class Clinica extends ManagedObject<_Clinica> implements _Clinica {}

class _Clinica {
  @ManagedColumnAttributes(primaryKey: true, autoincrement: true)  int seq_clinica;
  String nom_clinica;  
  int num_cnpj;
  @ManagedColumnAttributes(nullable:  true)  int cod_cnes;
  @ManagedColumnAttributes(nullable:  true)  bool ind_ativo;
  @ManagedColumnAttributes(nullable:  true)  DateTime dta_insert;
  @ManagedColumnAttributes(nullable:  true)  DateTime dta_update;
  static String tableName() {
    return "t_clinica";
  }
}
```

The problem is that it only works when I remove the property `num_cnpj` in the `_Clinica` Persistent Type. 

For example, here's the controller...

```Dart
class ClinicaController extends HTTPController {
    @httpGet getClinica() async {
      var clinicaQuery = new Query<Clinica>();
      var clinicas = await clinicaQuery.fetch();
      return new Response.ok(clinicas);
    }
}
```

without `num_cnpj` in the Persistent Type, the request gets an appropriate response...

```json
http://127.0.0.1:8000/clinicas
[{"seq_clinica":1,"nom_clinica":"Clinica Modelo","cod_cnes":null,"ind_ativo":true,"dta_insert":"2016-12-11T01:22:15.121523Z","dta_update":"2016-12-11T01:22:15.121523Z"}]
```

but with `num_cnpj` I get an exception...

```bash
[SEVERE] 2016-12-12 21:38:30.658901 aqueduct: 127.0.0.1 GET /clinicas 121ms 500 {user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36\nconnection : keep-alive\ncache-control : max-age=0\naccept : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\naccept-language : pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2\naccept-encoding : gzip, deflate, sdch, br\ndnt : 1\nhost : 127.0.0.1:8000\nupgrade-insecure-requests : 1\n} -  PostgreSQLSeverity.error : Connection closed or query cancelled. Detail: null Hint: null Table: null Column: null Constraint: null #0      PostgreSQLPersistentStore._executeQuery.<_executeQuery_async_body> (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:477:7)\n#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)\n#2      _RootZone.runBinary (dart:async/zone.dart:1410)\n#3      _FutureListener.handleError (dart:async/future_impl.dart:146)\n#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#6      _Future._completeError (dart:async/future_impl.dart:485)\n#7      _Future.timeout.<anonymous closure> (dart:async/future_impl.dart:741)\n#8      _RootZone.runBinary (dart:async/zone.dart:1410)\n#9      _FutureListener.handleError (dart:async/future_impl.dart:146)\n#10     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#11     _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#12     _Future._completeError (dart:async/future_impl.dart:485)\n#13     _SyncCompleter._completeError (dart:async/future_impl.dart:56)\n#14     _Completer.completeError (dart:async/future_impl.dart:27)\n#15     PostgreSQLConnection.query.<query_async_body> (package:postgres/src/connection.dart:229:3)\n#16     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)\n#17     _RootZone.runBinary (dart:async/zone.dart:1410)\n#18     _FutureListener.handleError (dart:async/future_impl.dart:146)\n#19     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#20     _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#21     _Future._completeError (dart:async/future_impl.dart:485)\n#22     _SyncCompleter._completeError (dart:async/future_impl.dart:56)\n#23     _Completer.completeError (dart:async/future_impl.dart:27)\n#24     PostgreSQLConnection._enqueue.<_enqueue_async_body> (package:postgres/src/connection.dart:308:3)\n#25     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)\n#26     _RootZone.runBinary (dart:async/zone.dart:1410)\n#27     _FutureListener.handleError (dart:async/future_impl.dart:146)\n#28     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#29     _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#30     _Future._completeError (dart:async/future_impl.dart:485)\n#31     _SyncCompleter._completeError (dart:async/future_impl.dart:56)\n#32     _Completer.completeError (dart:async/future_impl.dart:27)\n#33     _Query.completeError (package:postgres/src/query.dart:147:16)\n#34     PostgreSQLConnection._cancelCurrentQueries.<anonymous closure>.<anonymous closure> (package:postgres/src/connection.dart:319:11)\n#35     List.forEach (dart:core-patch/growable_array.dart:258)\n#36     PostgreSQLConnection._cancelCurrentQueries.<anonymous closure> (package:postgres/src/connection.dart:318:16)\n#37     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\n#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)\n
```

Any clues or workaround?

**Comment by joeconwaystk** [comment]
That sounds like an issue with the postgres driver. There was an outstanding PR for that driver that I merged and published just a moment ago (0.9.4+1). I think that may be your cause. If it's not, let me know.

**Comment by zidenis** [comment]
updated the driver to 0.9.4+1, but the problem persist, unfortunately.

looking at postgres logs, everything seems fine.

```
< 2016-12-11 17:18:37.139 BRT > LOG:  connection received: host=192.168.56.1 port=58113
< 2016-12-11 17:18:37.171 BRT > LOG:  connection authorized: user=cheese_app database=cheese
< 2016-12-11 17:18:37.190 BRT > LOG:  duration: 0.958 ms
< 2016-12-11 17:18:37.190 BRT > LOG:  duration: 0.540 ms
< 2016-12-11 17:18:37.190 BRT > LOG:  execute 000000000000: SELECT t_clinica.seq_clinica,t_clinica.nom_clinica,t_clinica.num_cnpj,t_clinica.cod_cnes,t_clinica.ind_ativo,t_clinica.dta_insert,t_clinica.dta_update FROM t_clinica 
< 2016-12-11 17:18:37.190 BRT > LOG:  duration: 0.062 ms
```

The exception raised doesn't reveal much for me

```
[SEVERE] 2016-12-13 20:17:41.678289 aqueduct: 127.0.0.1 GET /clinicas 109ms 500 {user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36\nconnection : keep-alive\ncache-control : max-age=0\naccept : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\naccept-language : pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2\naccept-encoding : gzip, deflate, sdch, br\ndnt : 1\nhost : 127.0.0.1:8000\nupgrade-insecure-requests : 1\n} -  PostgreSQLSeverity.error : Connection closed or query cancelled. Detail: null Hint: null Table: null Column: null Constraint: null #0      PostgreSQLPersistentStore._executeQuery.<_executeQuery_async_body> (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:477:7)\n#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)\n#2      _RootZone.runBinary (dart:async/zone.dart:1410)\n#3      _FutureListener.handleError (dart:async/future_impl.dart:146)\n#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#6      _Future._completeError (dart:async/future_impl.dart:485)\n#7      _Future.timeout.<anonymous closure> (dart:async/future_impl.dart:741)\n#8      _RootZone.runBinary (dart:async/zone.dart:1410)\n#9      _FutureListener.handleError (dart:async/future_impl.dart:146)\n#10     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#11     _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#12     _Future._completeError (dart:async/future_impl.dart:485)\n#13     _SyncCompleter._completeError (dart:async/future_impl.dart:56)\n#14     _Completer.completeError (dart:async/future_impl.dart:27)\n#15     PostgreSQLConnection.query.<query_async_body> (package:postgres/src/connection.dart:241:3)\n#16     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)\n#17     _RootZone.runBinary (dart:async/zone.dart:1410)\n#18     _FutureListener.handleError (dart:async/future_impl.dart:146)\n#19     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#20     _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#21     _Future._completeError (dart:async/future_impl.dart:485)\n#22     _SyncCompleter._completeError (dart:async/future_impl.dart:56)\n#23     _Completer.completeError (dart:async/future_impl.dart:27)\n#24     PostgreSQLConnection._enqueue.<_enqueue_async_body> (package:postgres/src/connection.dart:320:3)\n#25     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)\n#26     _RootZone.runBinary (dart:async/zone.dart:1410)\n#27     _FutureListener.handleError (dart:async/future_impl.dart:146)\n#28     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)\n#29     _Future._propagateToListeners (dart:async/future_impl.dart:671)\n#30     _Future._completeError (dart:async/future_impl.dart:485)\n#31     _SyncCompleter._completeError (dart:async/future_impl.dart:56)\n#32     _Completer.completeError (dart:async/future_impl.dart:27)\n#33     Query.completeError (package:postgres/src/query.dart:153:16)\n#34     PostgreSQLConnection._cancelCurrentQueries.<anonymous closure>.<anonymous closure> (package:postgres/src/connection.dart:331:11)\n#35     List.forEach (dart:core-patch/growable_array.dart:258)\n#36     PostgreSQLConnection._cancelCurrentQueries.<anonymous closure> (package:postgres/src/connection.dart:330:16)\n#37     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\n#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)\n
```

I was thinking that it could be related to the num_cnpj column's datatype (NUMERIC), but there is another column (cod_cnes) with the same datatype and working fine.

**Comment by joeconwaystk** [comment]
Ah, yes, that makes sense. The driver doesn't support the NUMERIC data type (or VARCHAR for that matter) and uses the binary protocol, so it's probably getting confused with a 16 byte integer. 

To support this, the driver would first have to add support for these types. This may not be too difficult, since the driver code is nice and clean. When it comes to Aqueduct supporting it, the effort probably won't be too difficult - but I wonder how the API for ManagedColumnAttributes should work?

Would you be able to take a look at the postgres driver, specifically https://github.com/stablekernel/postgresql-dart/blob/master/lib/src/postgresql_codec.dart? I can point in the right direction, but for now, I can't commit to adding that behavior any time soon.

**Comment by joeconwaystk** [comment]
And for some add'l info, the Aqueduct applies type annotations to the query string that the postgres driver supports, but strips out. For example, `INSERT INTO n (i1, i2) values (@i1:int4, @i2:int4)` tells the driver to use binary encoding for values i1 and i2 that are 4 byte integers. Without that type information, it uses a text representation for that particular value. Aqueduct always adds a type annotation, because it 'knows' the types going in based on ManagedPropertyType. But for a type it doesn't know, it apparently defaults to a type it does know and annotates it incorrectly. So perhaps it's enough of a workaround to have Aqueduct not apply the type annotation in the query string if it doesn't recognize the type, but there currently isn't a way to tell ManagedColumnAttributes to do that. I'm currently refactoring the code that builds the data model to figure out types, so if you can wait, it may be better to look at it after that.

**Comment by zidenis** [comment]
No problem. Thanks for this amazing tech.
Unfortunatelly, the magic of aqueduct does not have a good fit for my currently use cases. 
I will dig the PG driver code to see if I can help in supporting the use of other data types.

If the moment is appropriate, I would like to suggest a new feature: adding comment to the queries that points to the piece of code that calls it, like described in https://blog.heroku.com/postgres-essentials#track-the-source-of-your-queries
