### ISSUE TITLE
default template's test case is not exiting correctly

### ISSUE THREAD

**Issue by sclee15** [stablekernel/aqueduct#237]
After The Test
00:02 +5: All tests passed!
and the dart process waits.....and not exit.
I had to press ctrl+c to exit it.

**Comment by joeconwaystk** [comment]
Dart 1.23.0?

If so, this is being addressed in 2.0.3. Work is already complete in #235 and #236

**Comment by joeconwaystk** [comment]
Can you update to 2.0.3 (both project and cli) and replicate? Also, which OS are you on?

**Comment by sclee15** [comment]
i don't know how to update to 2.0.3
when i re activate CLI, it shows 2.1.0
and it is still happening.

**Comment by joeconwaystk** [comment]
OK, 2.1.0 is fine. I've found the issue where some ports are not being closed in the harness' stop method. This can be rectified in your application and I'll push out an update to Aqueduct with these changes in the template file shortly.

There are 3 steps.

1. In your sink subclass, declare a static variable for the logging server and change the assignment in `initializeApplication` from  the local variable`var loggingServer` to the declared static variable:

```dart
class WildfireSink extends RequestSink {
  // Add this declaration
  static LoggingServer loggingServer;
 ...
  static Future initializeApplication(ApplicationConfiguration config) async {
  ...
    // Remove 'var' from the beginning of this line
    loggingServer = configFileValues.logging.loggingServer;
```

2. In `test/harness/app.dart`, update the `stop` method to close some more things:

```dart
Future stop() async {
   // These two lines are new
    await WildfireSink.loggingServer?.stop();
    await sink?.context?.persistentStore?.close();

    application.logger?.clearListeners();
    await application?.stop();
  }
```

3. Run `pub upgrade` to get an updated version of `scribe`, the logging dependency.

Also, one more question - are you running with `pub run test` or `dart`? Seems to only occur when using the latter.

**Comment by joeconwaystk** [comment]
OK, I've pushed this up in 2.1.1 such that you don't need any of this code. Keeping this open until confirmation.

**Comment by sclee15** [comment]
I ran a test by type dart test/user_controller_test.dart

and it still waits.
however if I run pub run test it seems normal

**Comment by joeconwaystk** [comment]
Have you made modifications to it? Anything that opens a connection or stream of some kind? I was able to do the following on Ubuntu 16.04 and the tests exited correctly:

```
pub global activate aqueduct
aqueduct create foobar
cd footer
dart test test/user_controller_test.dart
```

**Comment by sclee15** [comment]
Oh, It needed to re create project.

I created  new project with new CLI and test seems working correctly.

Thank you.
